//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.03.03 at 09:32:17 PM EET
//

package ua.spro.soaphelloworld.loaneligibility;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="yearlyIncome" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="cibilScore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="employmentMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Setter
@Getter
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"customerName", "age", "yearlyIncome", "cibilScore", "employmentMode"})
@XmlRootElement(name = "CustomerRequest")
public class CustomerRequest {

  /**
   * -- GETTER -- Gets the value of the customerName property.
   *
   * <p>-- SETTER -- Sets the value of the customerName property.
   *
   */
  @XmlElement(required = true)
  protected String customerName;

  /**
   * -- GETTER -- Gets the value of the age property. -- SETTER -- Sets the value of the age
   * property.
   */
  protected int age;

  /**
   * -- GETTER -- Gets the value of the yearlyIncome property. -- SETTER -- Sets the value of the
   * yearlyIncome property.
   */
  protected long yearlyIncome;

  /**
   * -- GETTER -- Gets the value of the cibilScore property. -- SETTER -- Sets the value of the
   * cibilScore property.
   */
  protected int cibilScore;

  /**
   * -- GETTER -- Gets the value of the employmentMode property.
   *
   * <p>-- SETTER -- Sets the value of the employmentMode property.
   *
   */
  @XmlElement(required = true)
  protected String employmentMode;
}
